[package]
name = "grep"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argtool = { path = "../argtool" }
anyhow = "1.0.71"
